### ISSUE TITLE
application to a simple spring-mass system

### ISSUE THREAD

**Issue by tianyikillua** [mathLab/PyDMD#101]
I'm relatively new to the DMD method, so please point out the errors I may have made in applying PyDMD to the following simple spring-mass system (3 DoFs).

## Construct the snapshot matrix
The response corresponds to a given linear combinaison of the normal modes.
``` python
M = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

K = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 1]
])
omega2, V = linalg.eigh(K, M)
omega = np.sqrt(omega2)
t = np.linspace(0, 50, 500)
q = np.vstack([
    10 * np.cos(omega[0] * t),  # given linear combination of normal modes
    2 * np.cos(omega[1] * t),
    3 * np.cos(omega[2] * t)
])
X = V @ q  # snapshot matrix
```

## PyDMD

The obtained dynamics do not correspond to the given ones (at frequencies `omega`).
```
dmd = DMD(svd_rank=3)
dmd.fit(X)
for i, dynamic in enumerate(dmd.dynamics):
    plt.plot(t, dynamic.real, label=f"#{i:d}")
plt.legend()
plt.grid()
plt.tight_layout()
```

![](https://user-images.githubusercontent.com/4027283/64166567-a6537d00-ce47-11e9-963e-69b2bdc3fcc8.png)

Also, the reconstructed response (e.g., the 1st DoF) agrees poorly with the original one.
```
plt.plot(t, X[0], label="original")
plt.plot(t, dmd.reconstructed_data[0].real, label="DMD")
plt.legend()
plt.grid()
plt.tight_layout()
```

![](https://user-images.githubusercontent.com/4027283/64169541-4d3b1780-ce4e-11e9-9589-70c961578e35.png)

Where am I doing wrong?

**Comment by tianyikillua** [comment]
Ok, if my snapshot matrix is complex everything is fine now.
```
q = np.vstack([
    10 * np.exp(omega[0]*j * t),
    2 * np.exp(omega[1]*j * t),
    3 * np.exp(omega[2]*j * t)
])
X = V @ q  # snapshot matrix
```

![](https://user-images.githubusercontent.com/4027283/64172425-41068880-ce55-11e9-93d4-4a5c210b3285.png)

Should this be considered a bug?

**Comment by mtezzele** [comment]
Hi! Thank you for pointing it out. We will have a look at it. Meanwhile use complex matrices.

**Comment by benoitpaillard** [comment]
Hi all,
I ran into the same issue myself.

Using tutorial 1, and fitting only on real part does not work.

However, using HODMD with d>1 instead of simple DMD does work. This solves the issue both for tutorial 1 and the case presented above.

Any thoughts ?

**Comment by tianyikillua** [comment]
> Hi all,
> I ran into the same issue myself.
> 
> Using tutorial 1, and fitting only on real part does not work.
> 
> However, using HODMD with d>1 instead of simple DMD does work. This solves the issue both for tutorial 1 and the case presented above.
> 
> Any thoughts ?

Hi, I also tried HODMD with d > 1, but only `d in [4, 5, 6, 7]` reconstructs the original signal...

**Comment by tianyikillua** [comment]
Time delayed embedding is necessary, see https://github.com/andgoldschmidt/DMD/blob/master/Examples.ipynb

**Comment by tianyikillua** [comment]
So this is not a bug but requires a deeper understanding of the method. The HODMD method just applies time delayed embedding to the original snapshot matrix and can be used in case of insufficient spatial dimension. Note that `svd_rank` must be raised to necessary degrees (the default `svd_rank = 0` may results in lower values).

**Comment by benoitpaillard** [comment]
I'd like to add that using hod is not possible with DMDc, so delay embedding needs to be done by hand still. 
Thanks for the investigation and links Tianyi.
