### ISSUE TITLE
Sparsity Promoting DMD

### ISSUE THREAD

**Issue by adam2392** [mathLab/PyDMD#105]
Hi,

Are there plans to incorporate sparsity promoting DMD? 

Adding an option to post-process the modes using a convexopt procedure to identify modes? If truncation is sufficient, is there a good discussion for why?

If there is a need, and help is needed, happy to consider helping over the next few months when I have time.

Reference: http://people.ece.umn.edu/users/mihailo/papers/jovschnicPOF14.pdf

**Comment by mtezzele** [comment]
Hi @adam2392,

currently there are not plans to incorporate spDMD. If you want to help in this direction we would be very happy. I suggest you to have a look at the `_compute_amplitudes` method in the `DMDBase` class. 

If you have questions or need help do not hesitate to contact us!
