### ISSUE TITLE
Computation error when having negative eigenvalues

### ISSUE THREAD

**Issue by xlrobotics** [mathLab/PyDMD#115]
There's a numerical issue at line 90-91 of the file dmdc.py (there are several other places having the same issue), such that when self.eigs are negative, np.log() will return nan.

omega = old_div(np.log(self.eigs), self.original_time['dt'])
eigs = np.exp(omega * self.dmd_time['dt'])

Mathematically these two lines can be merged together to avoid having negative value inside the logarithm. 

I solved this by changing to
eigs = np.power(self.eigs, old_div(self.dmd_time['dt'], self.original_time['dt']))

Please let me know if there are better solutions, thanks!

**Comment by mtezzele** [comment]
Hi @xlrobotics, sorry for the late reply. Now this issue should be fixed with your solution, at least for dmdc (see #118). Thanks for letting us know the problem!
