### ISSUE TITLE
DMDc tutorial #7

### ISSUE THREAD

**Issue by benoitpaillard** [mathLab/PyDMD#116]
Hi all,
I reckon there is a mistake in DMD with control tutorial 7.
The tutorial says there are 25 snapshots created with 10 state variables, however the length of x0 is 25, so I'd say there are 25 state variables with 10 snapshots. Is that right ?

Thanks for your help

**Comment by ndem0** [comment]
Thanks for reporting @benoitpaillard!
We will check the tutorial and clear this point

**Comment by mtezzele** [comment]
@benoitpaillard you are right, there are 10 snapshots with 25 state variables. We are going to extend the tutorial about DMD with control in the next weeks by replicating some results of the original paper.
