### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by briandesilva** [mathLab/PyDMD#129]
Great package! I was just wondering if you had plans to create a new release any time soon. I see that there have been lots of improvements since the current version 0.2.1 was released in 2018. It looks like the documentation is up-to-date with the GitHub repo, but the version on PyPI isn't.

I'm not sure if others have run into this, but it took me a little while to realize the reason I was getting an error when I tried to call `DMD.predict` was because the documentation was ahead of the current PyPI version.

Edit: I should also mention that I'm currently working on a package based on the Koopman operator and was planning to make PyDMD a dependency. I'd feel better about doing so if a new release was made which included the features added after the last release in 2018.

**Comment by ndem0** [comment]
Dear @briandesilva, sorry for the confusion between the versions.
I uploaded the new release (created today) on PyPI  and updated the online documentation. Now I hope everything is more consistent. 
Thanks for reporting!

**Comment by briandesilva** [comment]
Thanks!
