### ISSUE TITLE
HODMD doesn't agree with the reference

### ISSUE THREAD

**Issue by chengzhanhong** [mathLab/PyDMD#132]
By looking at the code, the current HODMD seems to be a "Hankel-DMD"-- first stack the staggered data, next perform DMD on the new data. 

But I found the [code](https://github.com/LeClaincheVega/HODMD/blob/master/DMDd_SIADS.m) and paper for the original HODMD are different than the pydmd. Their first step is to reduce the data.

I think they are not equivalent.

**Comment by ndem0** [comment]
Hi @chengzhanhong, thanks for the warning! We'll check the consistency of our implementation in the next days and write you back!

**Comment by ndem0** [comment]
Dear @chengzhanhong, we've checked and you are right! The current HODMD implementation actually refers to Hankel-DMD. We'll fix as soon as possible, I keep open the issue just to warn about the fix.
