### ISSUE TITLE
Adding a DMD bounding box (probing/window) function in DMDBase class

### ISSUE THREAD

**Issue by edwinrajeevjo** [mathLab/PyDMD#144]
Hi, 
I am an active CFD user and I use DMD to understand turbulence in environmental flows. I recently wrote a function using pyDMD and my own bound box (window) function. The function chooses the data values within a box (min X coord, max X coord) and (min Y coord, max Y coord) from the snapshot matrix (my snapshot matrix has X and Y coordinates as the first 2 columns followed by the data) and can perform any of the DMD methods on this bound box. 
This can be added to the DMDBase class and can be called by any of the DMD methods. Is it alright if I incorporate this with the said class. I use it quite frequently with numerical and experimental data and found it very useful writing this function. I would like to contribute and can also create the test cases for this function.

Kindly do consider.

Regards
Edwin Rajeev

**Comment by mtezzele** [comment]
Dear @edwinrajeevjo , sorry for the late reply. I would suggest you to use a separate function which does the preprocessing you need. You just pass to the fit method the results of such preprocessing. It is too particular this functionality to be added in the package: the assumption on the structure of the matrices to fit is too strong. I am sorry.
