### ISSUE TITLE
Regularization Enhancement?

### ISSUE THREAD

**Issue by rajarshiroychowdhury** [mathLab/PyDMD#184]
Was wondering if an enhancement can be added when the input matrix is ill-conditioned. The warning saying the condition number is high certainly helps but I was wondering if it's possible to implement the regularization as described on page 8 of the Erichson et al paper attached below
[Random-DMD_Erichson.pdf](https://github.com/mathLab/PyDMD/files/7029255/Random-DMD_Erichson.pdf)
. I think this will at least give a way to handle the case of an ill-conditioned input matrix.

**Comment by mtezzele** [comment]
Dear @rajarshiroychowdhury, regularization is for sure a possible way to handle such problem. It is possible we will add this feature in the future. In the near term we are going to integrate new DMD versions. If you want to contribute on the regularization we would be very glad.

**Comment by rajarshiroychowdhury** [comment]
Thanks for the response @mtezzele! Appreciate it! I probably would have to dig through the code at some point and get this done, but I am sure the main developers can implement this pretty quickly. It seems like just adding another term with a parameter that the user might be able to specify while calling let's say hodmd. Again, I understand and appreciate the fact that possibly integrating new DMD variations is the near-term goal, but I just thought this should be relatively easy and straightforward for the developers than someone else who might need to dig into the code to figure out where exactly this should be added. Regardless, thank you!
