### ISSUE TITLE
MrDMD issue when fitting on non-complex data

### ISSUE THREAD

**Issue by blimblam-lab** [mathLab/PyDMD#235]
**Describe the bug**
As I haven't found anyone else with the same issue with mrDMD, I'm not sure whether this is a bug or whether I just need help. 
When applying mrDMD to real data I get an error indicating an unsuccessful complex value subtraction from real variables. If I Use complex data this issue doesn't happen.

**To Reproduce**
dmd = MrDMD(DMD(svd_rank=0),max_level=10, max_cycles=4) 
dmd.fit(steady)

**Expected behavior**
As far as my understanding goes, I would've expected no errors as I used the same code from the mrDMD tutorial where I had no issues.

**Output**
Traceback (most recent call last):
  File "/mrDMDPressureField.py", line 48, in <module>
    dmd.fit(steady)
  File "\pydmd\pydmd\mrdmd.py", line 434, in fit
    X -= newX
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'

**Comment by ndem0** [comment]
Dear @blimblam-lab,
sorry for the long delay. The issue looks just a problem related with the `dtype` of the input data. I tried to adjust it in #239.

Please, try to upgrade PyDMD (from source, not yet on `pip`) and let us know if you still have the problem!

**Comment by ndem0** [comment]
Dear @blimblam-lab, do you tested the new version of code? Still facing some problems using not-complex arrays?
