### ISSUE TITLE
Bad documentation link.

### ISSUE THREAD

**Issue by mphschmitt** [mathLab/PyDMD#243]
The README.md in the tutorials folder has a broken link to tutorial10: https://mathlab.github.io/PyDMD/tutorial10paramdmd.html
The filename seems ok, and the url is the same for all other tutorials in the same folder, so I am not quite sure why it doesn't work.

Here is what I have tried on my fork so far:
   - add the sphinx.ext.githubpages extension to conf.py
   - Add a config.yml file (usually for jekyll which should not be used here, but it was worth a try in case of a bug on github's side still using jekyll) including the docs/source/_tutorials folder (jekyll ignores files and folders whose name begins with an underscore).
   - I checked the logs of github action and everything seems to build without any error.

**Comment by ndem0** [comment]
Dear @mphschmitt, yes, you're right, we just need to upload the documentation online to make such link working. Soon the new release!

**Comment by mphschmitt** [comment]
Thanks!
