### ISSUE TITLE
Variable projection method for datasets collected at unevenly spaced sample times

### ISSUE THREAD

**Issue by heliogabale** [mathLab/PyDMD#253]
Hello
Is there a plan to implement the Optimized DMD using the variable projection method for datasets collected at unevenly spaced sample times as  proposed by Askham and Kutz (2018) in SIAM Journal of Dynamical System, vol17,no 1, pp 380-416

The authors released a MATLAB implementation at https://github.com/duqbo/varpro2
It has been ported to python https://github.com/kunert/py-optDMD (with a potential serious bug reported in the issue section) 
Best

**Comment by klapo** [comment]
I started updating/maintaining the python conversion following prompting by Dr. Kutz (see [my fork](https://github.com/klapo/pyoptDMD)). So far it exactly reproduces the MATLAB optDMD output for certain cases and qualitatively reproduces the MATLAB results when implementing it in a statistical bagging approach.

I'd love to contribute to the implementation of the optDMD in pydmd, however you all and Dr. Kutz decide to proceed.

That said, I think there is now a name space conflict for optDMD?

**Comment by klapo** [comment]
This issue should be closed by pull request #308
