### ISSUE TITLE
Tutorial 1 run on on one-dimensional Ornstein-Uhlenbeck process

### ISSUE THREAD

**Issue by soulhi-vz** [mathLab/PyDMD#282]
Hi,
Can you please help interpret what I am getting when I run tutorial 1 on one-dimensional Ornstein-Uhlenbeck process:
![image](https://user-images.githubusercontent.com/61634050/172713691-55bd99a0-8c81-4991-a117-5378f7a70011.png)
I got the results below:
print(mode.real)
[1.]
print(dmd.reconstructed_data)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
  Thanks
  /Said

**Comment by fAndreuzzi** [comment]
Hi @soulhi-vz, thank you for your report. Could you please provide a dataset such that we can reproduce the problem? Also, the entire code you're using in your experiment (i.e. `dmd = DMD(...)`) would be very useful, such that we can track the root cause.

**Comment by soulhi-vz** [comment]
Hi Francisco,
Attached the Jupyter notebook. Note that I have uploaded it as a text since I was not able to move it to github as ipynb
Thanks
/Said
[2022_TestPyDMD_June.ipynb.txt](https://github.com/mathLab/PyDMD/files/8869764/2022_TestPyDMD_June.ipynb.txt)

**Comment by soulhi-vz** [comment]
Hi Francisco,
Thanks for the prompt answer. It was very helpful
/Said
