### ISSUE TITLE
Tutorial 3

### ISSUE THREAD

**Issue by lightbearer88** [mathLab/PyDMD#302]
Hi,

I was trying out tutorial 3 (specifically, this one: https://mathlab.github.io/PyDMD/tutorial3mrdmd.html) and when I got to the line
`dmd = MrDMD(svd_rank=-1, max_level=7, max_cycles=1)` , I got the error `TypeError: __init__() got an unexpected keyword argument 'svd_rank' ` . I believe this is a bug as the syntax differs from the documentation: https://mathlab.github.io/PyDMD/mrdmd.html

**Comment by fAndreuzzi** [comment]
Hi @lightbearer88, thanks for the report. https://mathlab.github.io/PyDMD/tutorial3mrdmd.html file is an outdated version of `tutorial3`, you can find the up-to-date Jupyter Notebook in `tutorials/tutorial3/`.

@ndem0 we should probably update the notebook

**Comment by mtezzele** [comment]
@fAndreuzzi should we close this?
