### ISSUE TITLE
When importing from pydmd.plotter: ModuleNotFoundError: No module named 'pydmd.plotter'

### ISSUE THREAD

**Issue by Conet1502** [mathLab/PyDMD#328]
**Describe the bug**
ModuleNotFoundError: No module named 'pydmd.plotter'

**To Reproduce**
Using python 3.10.0

from pydmd import DMD
 from pydmd.plotter import plot_eigs

**Expected behavior**
For the code not to have an Error on import

**Output**
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_32888\3246109997.py in <module>
      6 
      7 from pydmd import DMD
----> 8 from pydmd.plotter import plot_eigs
      9 dmd = DMD(svd_rank=2)
     10 dmd.fit(X11.T)

ModuleNotFoundError: No module named 'pydmd.plotter'

**Comment by fAndreuzzi** [comment]
Hi @Conet1502, I suspect you installed a version which is not up-to-date with the code on GitHub. 

I suggest the following:
```bash
# just to be sure
pip3 uninstall pydmd

# download PyDMD code
git clone https://github.com/mathLab/PyDMD.git

cd PyDMD
pip3 install .
```

This will install PyDMD from source, therefore you'll have the latest changes. `pydmd.plotter` is a pretty new component.

**Comment by Conet1502** [comment]
I pip3 uninstall and installed pydmd.

Still getting the same error.

**Comment by fAndreuzzi** [comment]
@Conet1502 Please try this (assuming you're in the `PyDMD` directory which you downloaded with `git clone` in the sequence of command I shared in my last message):
```
python3 -m venv venv
source venv/bin/activate
pip install .
```

And then try if `pydmd.plotter` can be imported.

**Comment by Conet1502** [comment]
Cool that worked, weird that pip3 pydmd didn't work.

**Comment by fAndreuzzi** [comment]
I guess it was some weird installation problem, let me know if you encounter other issues.
