### ISSUE TITLE
Parts of pyDMD not importing properly

### ISSUE THREAD

**Issue by moonlians** [mathLab/PyDMD#333]
**Describe the bug**
ImportError: cannot import name 'Havok' from 'pydmd' (C:\Users\x\anaconda3\envs\SVD\lib\site-packages\pydmd\__init__.py)

Certain parts of pyDMD aren't importing properly. Havok, Plotter, and Snapshots all have this problem.
I have tried using a clean environment, and installing with pip and with cloning github.

**Comment by fAndreuzzi** [comment]
Hi @moonlians, thanks for the report. 

I'm going to try reproducing the problem, could you please dump the exact sequence of commands you're using (from `git clone` to where you try to import the modules, including also `pip install`). Thanks!

**Comment by moonlians** [comment]
I'm still getting module not found:

  File "C:\Users\x\AppData\Local\Temp\ipykernel_10788\788030302.py", line 1, in <module>
    import pydmd.plotter

ModuleNotFoundError: No module named 'pydmd.plotter'


  File "C:\Users\x\AppData\Local\Temp\ipykernel_10788\2118356530.py", line 1, in <module>
    import pydmd.snapshots

ModuleNotFoundError: No module named 'pydmd.snapshots'

Strangely, HAVOK is also not working for me again now... I went back to my history to try to understand why it worked before, but I couldn't replicate it, sorry.

    from pydmd import HAVOK

ImportError: cannot import name 'HAVOK' from 'pydmd' (C:\Users\x\anaconda3\envs\DMD\lib\site-packages\pydmd\__init__.py)

**Comment by fAndreuzzi** [comment]
`snapshots` and `plotter` are not yet distributed with the version you get with `pip install pydmd`. I suggest uninstalling PyDMD and then re-installing from source just to be sure. I did the following:

```python
$ pip uninstall pydmd
$ git clone https://github.com/mathLab/PyDMD.git
$ pip install PyDMD/
$ python3
>>> import pydmd.snapshots
>>> import pydmd.plotter
>>> from pydmd import HAVOK
```
and I get no errors. I didn't use any virtual environment.

**Comment by moonlians** [comment]
Thanks, that works!

**Comment by fAndreuzzi** [comment]
I'm glad it works! Please re-open the issue if you encounter any other problem
