### ISSUE TITLE
Running tutorial #2

### ISSUE THREAD

**Issue by brendanjmeade** [mathLab/PyDMD#50]
Running the 2nd IPython notebook demo:

https://github.com/mathLab/PyDMD/blob/master/tutorials/tutorial-2-adv-dmd.ipynb

I get the following error under python 2.7 (anaconda install) on OS X (10.13.2):
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-d38bcaf550d6> in <module>()
----> 1 dmd = DMD(svd_rank=1, tlsq_rank=2, exact=True, opt=True)
      2 dmd.fit(snapshots)
      3 dmd.plot_modes_2D(figsize=(12,5))

TypeError: __init__() got an unexpected keyword argument 'opt'

User error or bug?

**Comment by mtezzele** [comment]
Hi, I suppose you installed the package via pip. Unfortunately it's not updated. Nicola Demo will upload the last version of the package in the morning. We will try to keep it updated. In general if you want the latest version you can also install the package via python setup.py install after cloning the repository. 
Thank you for noticing the issue.

**Comment by ndem0** [comment]
I just uploaded the last version on PyPi, you should able to install it via pip. I tried to run the second tutorial with the updated version, and everything works fine. Please, let us know if you  still have problems.

**Comment by brendanjmeade** [comment]
Thanks for the fix.  Works perfectly now.  This is an amazing library for so many problems!

**Comment by mtezzele** [comment]
Thank you! We try our best ;)
