### ISSUE TITLE
DMD with control

### ISSUE THREAD

**Issue by loiseaujc** [mathLab/PyDMD#59]
Hi guys,

I have been working with DMD for quite a while, essentially on very large-scale dynamical systems from fluid dynamics for which I needed to implement the algorithms directly within my flow solver. I am now moving on to smaller problems, for which using pre-existing libraries is much more suited and yours comes as a natural choice.

One of these problems is that of the nonlinear control of a two-dimensional flow. For that purpose, I plan to use DMD with Control (see Ref. [1]). Do you guys already have plans to implement DMDc?

Regards,
JC

[1] Proctor, Joshua L., Steven L. Brunton, and J. Nathan Kutz. "Dynamic mode decomposition with control." SIAM Journal on Applied Dynamical Systems 15.1 (2016): 142-161.

**Comment by mtezzele** [comment]
Hi,
the plan is to release the Higher Order DMD in the next weeks. Up to now we don't have plans regarding the DMD with control. If you are interested in implementing it we can help you, otherwise we can work on that in the next months.

Best,
Marco

**Comment by loiseaujc** [comment]
Good to know about HODMD. Haven't really used it myself yet though.

Regarding DMD with Control, Steven Brunton and I are about to use it for a project of ours. I already have a basic working implementation written in python. I would be happy to contribute by taking care of the DMDc implementation in PyDMD myself. I will be quite busy until mid-March though. By then, I should be able nonetheless to find some time to get familiar with your coding standards and tests. Final piece of code may be ready and cross-validated by the end of March.

**Comment by mtezzele** [comment]
Perfect! Let's remain in touch then! If we will implement something by the end of March about DMDc we will let you know before opening a PR.

**Comment by ndem0** [comment]
Implemented in #68
