### ISSUE TITLE
Low-rank DMD: optimal solution in polynomial time

### ISSUE THREAD

**Issue by loiseaujc** [mathLab/PyDMD#85]
Hi guys,

I was wondering if you had seen this [paper](https://arxiv.org/pdf/1610.02962.pdf)?

The authors have shown that all of the DMD algorithms proposed so far actually compute only a sub-optimal solution to the DMD minimization problem. More importantly, they come up with a closed-form solution that is actually the optimal solution.

Not sure how to proceed regarding its implementation. Do you think it would be worth adding a keyword to the DMD object to specify which algorithm to use (e.g. the original Schmid's algorithm or this optimal one) when fitting the model?

**Comment by mtezzele** [comment]
Hi! Thanks for recommending the paper. We were aware of this closed-form, just never found the time to implement it in the software. It is in our pipeline for the future developments for sure! 
If you want to help us in this we will assist you...

**Comment by loiseaujc** [comment]
I have just forked the repo and started to work on it. For the sake of simplicity, I have started to implement it into a new class, albeit I think it should eventually be merged with the original DMD class but that is up to you to decide.

**Comment by mtezzele** [comment]
Fantastic! When you have done we can review the code together and find the best way to integrate it in the package. Thank you very much!

**Comment by loiseaujc** [comment]
Hey guys,

I am pretty much done. I am currently on paternity leave so I am working only on and off on it.
I still have a couple of small things to finish. Should be able to send the PR early next week (if I have time).

**Comment by mtezzele** [comment]
Hi! Thank you very much for the contribution. 
Because of national holidays, please be patient, we will review the code next week.

**Comment by loiseaujc** [comment]
Hej,

No problem. I am on paternity leave right now and I start back on Monday. Next week may be extremely busy for me after these two weeks off so I just wanted to send the PR asap so that you guys can start reviewing it whenever you have time without having to wait for me to find a small slot in my schedule :)

**Comment by mtezzele** [comment]
Implemented in #87
