### ISSUE TITLE
Rank selection issue in `_compute_svd`

### ISSUE THREAD

**Issue by loiseaujc** [mathLab/PyDMD#88]
Hi guys,

I have noted a small issue with the rank selection in `_compute_svd(X, svd_rank)` when user prescribes a desired cumulative energy (i.e. a truncation error). Line 242 of `dmdbase.py`, the code reads

`cumulative_energy = np.cumsum(s / s.sum())`

However, the energy in POD analysis is related to the square of the singular values, not the singular values themselves. The code should instead read

`cumulative_energy = np.cumsum( s**2 / (s**2).sum() )`

This is pretty straightforward to modify so should I send a PR or do you guys wanna handle it?

**Comment by mtezzele** [comment]
You are right, thank you! I will fix this, no problem!

**Comment by mtezzele** [comment]
Fixed in #89
