### ISSUE TITLE
Computing DmD amplitudes get Error: numpy.linalg.LinAlgError: Incompatible dimensions

### ISSUE THREAD

**Issue by ElHouas** [mathLab/PyDMD#91]
Hi PyDMD team,

I am using PyDMD in my MSc Thesis at Imperial College.

I am experiencing issues when computing the amplitudes of the modes, my code is the following:

##Assign the array of the data containing the snapshots to the variable snapshots
snapshots = uvec_315_time.T

#Create dmd object using PyDMD library
dmd = DMD(svd_rank=0, tlsq_rank=0, exact=True, opt=True)
dmd.fit(snapshots)

#Spectral and spatial modes plot
eigs = dmd.eigs
modes = dmd.modes
amplitudes = DMDBase._compute_amplitudes(modes, snapshots, eigs, opt=True)

print(amplitudes)

I am getting the error of numpy.linalg.LinAlgError: Incompatible dimensions, should I change the code of the function or I have something wrong in my data.

Note that I want to reproduce the following plot: 
https://www.researchgate.net/figure/Amplitude-distribution-of-the-averaged-dynamic-modes-as-a-function-of-Strouhal-number-of_fig3_278646580

Thank you in advance

**Comment by mtezzele** [comment]
Hi! I would suggest to use the following line:
`amplitudes = dmd._b`

I guess we can add a property to return the amplitudes :)
Let me know if this fixes the issue.

**Comment by ElHouas** [comment]
> Hi! I would suggest to use the following line:
> `amplitudes = dmd._b`
> 
> I guess we can add a property to return the amplitudes :)
> Let me know if this fixes the issue.

Thank you for your quick response, I really appreciate it.

It works without error, it returned several complex numbers, I guess that the imaginary part represents the exponential growth and the real part represents the temporal frequency. Am I right?

Cheers :)

**Comment by ndem0** [comment]
Hi @ElHouas, the amplitudes are the coefficients that minimize the reconstruction of the system. I suppose you meant the eigenvalues of DMD operator, whose imaginary parts actually give information about the frequencies. Try to look at the `eigs` attribute or, since the pull request #92 , to the attribute `frequency` which provides the DMD spectrum. We implemented it just yesterday, so don't forget to download the latest version of the package.
