### ISSUE TITLE
Plot modes in 3D

### ISSUE THREAD

**Issue by ElHouas** [mathLab/PyDMD#93]
Dear team,

I am wondering if there is an implemented option to plot the modes in 3D. If not, could you give a small guidance of how to change the dmd._plot_modes_2D function to make it 3D.
Adding a third component of the domain to lines listed below would be enough?

        # If domain dimensions have not been passed as argument,
        # use the snapshots dimensions
        if x is None and y is None:
            x = np.arange(self._snapshots_shape[0])
            y = np.arange(self._snapshots_shape[1])

        xgrid, ygrid = np.meshgrid(x, y)

        if index_mode is None:
            index_mode = list(range(self._modes.shape[1]))
        elif isinstance(index_mode, int):
            index_mode = [index_mode]

Thanks for your time and attention

Cheers

Ismael

**Comment by mtezzele** [comment]
Feel free to add a new method to the class for your needs.

Best,
Marco
