### ISSUE TITLE
Will there be support for multi-resolution higher-order DMD? 

### ISSUE THREAD

**Issue by asrvsn** [mathLab/PyDMD#96]
Is that a thing which has been developed yet?

Alternatively, is there a way to pull out the higher-order transform, and feed that to the MrDMD? 

Thank you so much for this library.

**Comment by ndem0** [comment]
Hi @ooblahman, at the moment the feature you're asking is not implemented yet. But we plan to add the support for some *hybrid* versions in the next months, so stay tuned!

**Comment by ndem0** [comment]
From #162, `MrDMD` take as input a `DMD` (and variants) object, which enable to pass a `HODMD` class and perform the multi-resolution higher-order case.
